name: Lint and Format

on: 
  push:
    branches:
      - main
      
jobs:
  lint_and_format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff

      - name: Run Ruff Lint and Fix
        run: |
          ruff check --fix
          ruff format
          
